[pytest]

testpaths = test
python_files = *test*.py
python_classes = *Test*
python_functions = *test*

markers =
    ui: UI tests
    api: API tests

addopts =
    -v
    -s
    --tb=short
    --alluredir=allure-results
    --strict-markers